CREATE FUNCTION F_TK_SLTungSanPham (@START DATE,@FINISH DATE)
RETURNS @DS3 TABLE(MASP NCHAR(30),TENSP NVARCHAR(50),SOLUONG INT)
AS
	BEGIN
		DECLARE @MAMONAN NCHAR(30),@TENMONAN NVARCHAR(50),@SOLUONG INT
		DECLARE CS_DS3 CURSOR FOR SELECT MAMONAN,TENMONAN FROM MONAN
		OPEN CS_DS3
		FETCH NEXT FROM CS_DS3 INTO @MAMONAN,@TENMONAN
		WHILE(@@FETCH_STATUS=0)
			BEGIN
				SET @SOLUONG=(SELECT SUM(CT.SOLUONG) FROM CHITIETHOADON CT,HOADON HD WHERE MAMONAN=@MAMONAN AND HD.MAHD=CT.MAHD AND HD.NGAYTHANHTOAN BETWEEN @START AND @FINISH)
				IF(@SOLUONG IS NULL)
					SET @SOLUONG=0
				INSERT INTO @DS3 VALUES(@MAMONAN,@TENMONAN,@SOLUONG)
				FETCH NEXT FROM CS_DS3 INTO @MAMONAN,@TENMONAN
			END
		CLOSE CS_DS3
		DEALLOCATE CS_DS3
		RETURN
	END
GO

CREATE FUNCTION F_TK_TienTungSanPham(@START DATE,@FINISH DATE)
RETURNS @DS2 TABLE(MASP NCHAR(30),TENSP NVARCHAR(50),THANHTIEN FLOAT)
AS
	BEGIN
		DECLARE @MASP NCHAR(30),@TENSP NVARCHAR(50),@THANHTIEN FLOAT
		DECLARE CS_DS2 CURSOR FOR SELECT MAMONAN,TENMONAN FROM MONAN
		OPEN CS_DS2
		FETCH NEXT FROM CS_DS2 INTO @MASP,@TENSP
		WHILE(@@FETCH_STATUS=0)
			BEGIN
				SET @THANHTIEN=(SELECT SUM(CT.SOLUONG *SP.DONGIA) FROM CHITIETHOADON CT,HOADON HD,MONAN SP WHERE CT.MAMONAN=@MASP AND SP.MAMONAN=CT.MAMONAN AND HD.MAHD=CT.MAHD AND NGAYTHANHTOAN BETWEEN @START AND @FINISH)
				IF(@THANHTIEN IS NULL)
					SET @THANHTIEN=0
				INSERT INTO @DS2 VALUES(@MASP,@TENSP,@THANHTIEN)
				FETCH NEXT FROM CS_DS2 INTO @MASP,@TENSP
			END
		CLOSE CS_DS2
		DEALLOCATE CS_DS2
		RETURN
	END
GO

CREATE TRIGGER CapNhatSLSanPhamQuaPhieuGoi ON CHITIETDATBAN
FOR INSERT
AS
	BEGIN
		DECLARE CS_CapNhatSLSanPham CURSOR FOR SELECT MAMONAN,SOLUONG FROM inserted
		DECLARE @MAMONAN INT,@SOLUONG INT
		OPEN  CS_CapNhatSLSanPham
		FETCH NEXT FROM  CS_CapNhatSLSanPham INTO @MAMONAN,@SOLUONG
		WHILE(@@FETCH_STATUS=0)
			BEGIN
				UPDATE MONAN
				SET SOLUONG=SOLUONG-@SOLUONG
				WHERE MAMONAN=@MAMONAN
				FETCH NEXT FROM  CS_CapNhatSLSanPham INTO @MAMONAN,@SOLUONG
			END
		CLOSE CS_CapNhatSLSanPham
		DEALLOCATE CS_CapNhatSLSanPham
	END
GO

CREATE TRIGGER CapNhatSLSanPhamuUpdateQuaPhieuGoi ON CHITIETDATBAN
FOR UPDATE
AS
	BEGIN
		DECLARE CS_CapNhatSLSanPham CURSOR FOR SELECT MAMONAN,SOLUONG FROM inserted
		DECLARE @MAMONAN INT,@SOLUONG INT,@SOLUONGDELETE INT
		SET @SOLUONGDELETE=(SELECT SOLUONG FROM deleted )
		OPEN  CS_CapNhatSLSanPham
		FETCH NEXT FROM  CS_CapNhatSLSanPham INTO @MAMONAN,@SOLUONG
		WHILE(@@FETCH_STATUS=0)
			BEGIN
				UPDATE MONAN
				SET SOLUONG=SOLUONG-(@SOLUONG-@SOLUONGDELETE)
				WHERE MAMONAN=@MAMONAN
				FETCH NEXT FROM  CS_CapNhatSLSanPham INTO @MAMONAN,@SOLUONG
			END
		CLOSE CS_CapNhatSLSanPham
		DEALLOCATE CS_CapNhatSLSanPham
	END
GO

CREATE TRIGGER CapNhatSLSanPhamuDeleteQuaPhieuGoi ON CHITIETDATBAN
FOR DELETE
AS
	BEGIN
		DECLARE CS_CapNhatSLSanPham CURSOR FOR SELECT MAMONAN,SOLUONG FROM deleted
		DECLARE @MAMONAN INT,@SOLUONG INT
		OPEN  CS_CapNhatSLSanPham
		FETCH NEXT FROM  CS_CapNhatSLSanPham INTO @MAMONAN,@SOLUONG
		WHILE(@@FETCH_STATUS=0)
			BEGIN
				UPDATE MONAN
				SET SOLUONG=SOLUONG+@SOLUONG
				WHERE MAMONAN=@MAMONAN
				FETCH NEXT FROM  CS_CapNhatSLSanPham INTO @MAMONAN,@SOLUONG
			END
		CLOSE CS_CapNhatSLSanPham
		DEALLOCATE CS_CapNhatSLSanPham
	END
GO

CREATE PROC disableTrigger
AS
DISABLE TRIGGER CapNhatSLSanPhamuDeleteQuaPhieuGoi ON CHITIETDATBAN;
GO

CREATE PROC enableTrigger
AS
ENABLE TRIGGER CapNhatSLSanPhamuDeleteQuaPhieuGoi ON CHITIETDATBAN
GO